apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: delfin-task
  name: delfin-task
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: delfin-task
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: delfin-task
    spec:
      containers:
        - args:
            - task
          env:
            - name: OS_COORDINATION__BACKEND_SERVER
              value: redis:6379
            - name: OS_DEFAULT__TRANSPORT_URL
              value: rabbit://delfinuser:delfinpass@rabbitmq:5672//
            - name: OS_PROMETHEUS_EXPORTER__METRICS_DIR
              value: /var/lib/delfin/metrics
          image: sodafoundation/delfin:exporter
          name: delfin-task
          resources: {}
          volumeMounts:
            - mountPath: /etc/delfin
              name: delfin-config1
            - mountPath: /var/lib/delfin
              name: delfin-lib
            - mountPath: /var/lib/delfin/metrics
              name: metrics-dir
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /var/lib/delfin
          name: delfin-lib
        - hostPath:
            path: /var/lib/delfin/metrics
          name: metrics-dir
        - name: delfin-config1
          configMap:
            name: delfin-config
status: {}
